# BlueDwarf tunnel appveyor.yml script

version: '{branch}-{build}'

branches:
  only:
    - master

before_build:
  nuget restore

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

configuration: Release
platform: Any CPU

build:
  parallel: true   
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

environment:
  pfxKey:
    secure: Hsqip29o34bngMSg6CWzSVejHiqcoxFs9tZRyVUHZPU=

deploy:
  provider: NuGet
  api_key:
    secure: rEYnR9JThbc6x8DdCo1K8+fgsGKzjNKzTZsldXFLYMm/tFPC7JWWvuKpVTrDBd+g
  skip_symbols: false

after_test:
  - ps: $pfxKeyS = ConvertTo-SecureString $env:pfxKey -AsPlainText -Force
  - ps: $pfx = new-object System.Security.Cryptography.X509Certificates.X509Certificate2
  - cd
  - ps: $pfx.import("..\Tools\2d2fb0f6778ab96c5b484171e22b4f08.pfx", $pfxKeyS, "Exportable,PersistKeySet")
  - ps: $store = new-object System.Security.Cryptography.X509Certificates.X509Store("CurrentUser", "Me")
  - ps: $store.open("MaxAllowed")
  - ps: $store.add($pfx)
  - ps: $store.close()
  - msbuild /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:Publish /property:ApplicationRevision=%APPVEYOR_BUILD_NUMBER% /property:PublishUrl=.\Publish

artifacts:
  - path: '.\Publish\**\*.*'
